{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.oss.licenses",
    "module": "parser",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "parser-1.0.aar",
          "url": "parser-1.0.aar",
          "size": 10222,
          "sha512": "d2350068f1b3e7a0cc85e0ef322a765d77586cc70d50c558b5710df9632e715af8d2fc18e545af900811f25234550cd8dd2bce8afc00e1ecdb3b7c45276b6d2c",
          "sha256": "6d573e2facadfb3cf459e6d61e7da60884478758cda955da8fdfd0895ef9b671",
          "sha1": "8490f4e9168a49868671b071fa0d65b4ad29d046",
          "md5": "4fd771872c8b8f16606484484b5f1888"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "parser-1.0.aar",
          "url": "parser-1.0.aar",
          "size": 10222,
          "sha512": "d2350068f1b3e7a0cc85e0ef322a765d77586cc70d50c558b5710df9632e715af8d2fc18e545af900811f25234550cd8dd2bce8afc00e1ecdb3b7c45276b6d2c",
          "sha256": "6d573e2facadfb3cf459e6d61e7da60884478758cda955da8fdfd0895ef9b671",
          "sha1": "8490f4e9168a49868671b071fa0d65b4ad29d046",
          "md5": "4fd771872c8b8f16606484484b5f1888"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "parser-1.0-sources.jar",
          "url": "parser-1.0-sources.jar",
          "size": 4361,
          "sha512": "8a7532a56d2d6f19ae3b727e2d626a1970e575679c6d0530c7b2c0382ee42b65e9d614d4aa5ded7ebdd542e03ec4f59c7020b8e487ceee24abe278d7e28e78ce",
          "sha256": "727ceefef5c39b2ad918131aa3a44f33f84c981646febad048cf5bb237028caa",
          "sha1": "cdaba62ae62f06a6c17b98df19734b97299ae9b4",
          "md5": "8c389d8e9334acae6b6f4a3feb3e036f"
        }
      ]
    }
  ]
}
